"""
REGIME — Precomputed example cache

A small on-disk cache of full `/api/analyze` payloads for a curated set of
showcase tickers. It serves two purposes:

1. **Instant first paint.** The default ticker and the example chips load from
   this cache in milliseconds instead of waiting 10-25s for a live fetch + HMM
   fit. A visitor sees a complete, animated dashboard immediately.
2. **Resilience.** If Yahoo Finance is unreachable, a live query for a showcase
   ticker falls back to its cached payload so the demo never shows a dead screen.

The cache is regenerated by `scripts/build_cache.py` (no API key required — it
only uses public yfinance data) and committed to the repo.
"""

import json
from pathlib import Path
from typing import Optional

CACHE_DIR = Path(__file__).resolve().parent / "cache"

# Curated showcase tickers. Only those with a cache file on disk are surfaced as
# example chips, so generation failures degrade gracefully (the chip just
# disappears) rather than producing a broken button. India-first, with a couple
# of globally familiar references.
EXAMPLES: list[dict[str, str]] = [
    {
        "ticker": "RELIANCE.NS",
        "name": "Reliance Industries",
        "market": "India · NSE",
        "blurb": "India's largest company through the 2020 crash and recovery.",
    },
    {
        "ticker": "^NSEI",
        "name": "NIFTY 50",
        "market": "India · Index",
        "blurb": "India's benchmark index — watch the Crisis flare in early 2020.",
    },
    {
        "ticker": "^BSESN",
        "name": "SENSEX",
        "market": "India · Index",
        "blurb": "The 30-stock BSE benchmark over the full cycle.",
    },
    {
        "ticker": "^GSPC",
        "name": "S&P 500",
        "market": "US · Index",
        "blurb": "US large caps — COVID crash, the 2022 bear, the AI rally.",
    },
    {
        "ticker": "AAPL",
        "name": "Apple",
        "market": "US · NASDAQ",
        "blurb": "A single mega-cap's regimes across seven years.",
    },
]


def _slug(ticker: str) -> str:
    """Filesystem-safe slug for a ticker (^NSEI → IDX_NSEI, RELIANCE.NS → RELIANCE_NS)."""
    return (
        ticker.upper()
        .replace("^", "IDX_")
        .replace(".", "_")
        .replace("-", "_")
    )


def cache_file(ticker: str) -> Path:
    return CACHE_DIR / f"{_slug(ticker)}.json"


def load_cached(ticker: str) -> Optional[dict]:
    """Return the cached analyze payload for a ticker, or None if absent/corrupt."""
    fp = cache_file(ticker)
    if not fp.exists():
        return None
    try:
        with open(fp, encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, OSError):
        return None


def save_cached(ticker: str, payload: dict) -> None:
    """Write an analyze payload to the cache for a ticker."""
    CACHE_DIR.mkdir(exist_ok=True)
    with open(cache_file(ticker), "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False)


def list_examples() -> list[dict]:
    """Return metadata for every showcase ticker that has a cached payload."""
    out: list[dict] = []
    for ex in EXAMPLES:
        payload = load_cached(ex["ticker"])
        if not payload:
            continue
        dates = payload.get("dates") or []
        out.append(
            {
                **ex,
                "current_regime": payload.get("current_regime"),
                "start": dates[0] if dates else None,
                "end": dates[-1] if dates else None,
                "sessions": len(dates),
            }
        )
    return out
